export default {
    UPDATE_COMPLETE: 'UPDATE_COMPLETE',
    UPDATE_PROGRESS: 'UPDATE_PROGRESS',
    RESET_PROGRESS: 'RESET_PROGRESS',
    TOGGLE_AUTO_UPDATE: 'TOGGLE_AUTO_UPDATE',
    CURRENCIES_UPDATE: 'CURRENCIES_UPDATE',
    CONFIG_VALIDATION: 'CONFIG_VALIDATION',
    CHANGE_AUTO_UPDATE_INTERVAL: 'CHANGE_AUTO_UPDATE_INTERVAL',
    SET_AUTO_UPDATE: 'SET_AUTO_UPDATE',
    SAVE_CONFIGURATION: 'SAVE_CONFIGURATION'
};